apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: pop-stack
version: 1.0.0

dependencies:
- name: universal
  version: ">=1.0.0"
  repository: file://../universalchart
  condition: sample-component.enabled
  alias: sample-component
