global:
  # Variables that are used to build env vars for the specific environment
  vars:
    ENV_NAME: "dev"
    BASE_DB_URL: "Dummy variable"
    BASE_DB_OPTS: "usessl=true&sslmode=require"
    BASE_DB_USER: "postgres"
    BASE_DB_PASS: "nopass"

    BASE_REDIS_HOST: "x-k8s-redis-headless"
    BASE_REDIS_USER: "default"
    BASE_REDIS_PASS: "mypasshere"
  # Env variables that are applied to every service
  env:
    AWS_REGION: "eu-central-1"

sample-component:
  enabled: true
  appId: sample-component
  externalsecretEnv:
    enabled: true
    env:
    - name: DATASOURCE_USERNAME
      key: "Dummy variable" 
      property: username
    - name: SAMPLE_VAR
      key: "Dummy variable"
      property: password
  cm:
    enabled: true
    env:
      APPLICATION_PORT: 8080
    dynamic:
      DATASOURCE_DB_URL: "jdbc:postgresql://{{ .Values.global.vars.BASE_DB_URL }}:5432/postgres?{{ .Values.global.vars.BASE_DB_OPTS }}"
      REGION_NAME: "{{ .Values.global.env.AWS_REGION }}"
      AWS_REGION: "{{ .Values.global.env.AWS_REGION }}"
      AWS_DEFAULT_REGION: "{{ .Values.global.env.AWS_REGION }}"
      REDIS_HOST: "{{ .Values.global.vars.BASE_REDIS_HOST }}"
      REDIS_PORT: "6379"
      REDIS_USE_SSL: "false"
      REDIS_USERNAME: "{{ .Values.global.vars.BASE_REDIS_USER }}"

  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/actions.response-503: |
        {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"503","messageBody":"503 Service Unavailable"}}
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
        { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/group.name: public
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/success-codes: 200-404
      alb.ingress.kubernetes.io/target-type: ip
      kubernetes.io/ingress.class: alb
    dynamic:
      enabled: true
      nsPrefix: false
      tls: true
      baseDomain: itgix.eu
#      cfgs:
#      - name: sample-component
#        paths:
#          - /
#        port: 80

  service:
    enabled: true
    external: false
    ports:
    - name: application
      port: 80
      protocol: TCP
      targetPort: application

  serviceAccount:
    enabled: false
    name: "aurora-tc-irsa"
    annotations: {}

  deployment:
    enabled: true

    serviceAccountName:
      enabled: false
      name: "aurora-tc-irsa"

    replicaCount: 1

    image:
      pullSecret:
        enabled: false
        secretName: "-"
      ecr: ""
      repository: "nginx"
      tag: "1.27-alpine3.20-slim"
      pullPolicy: "Always"

    securityContext:
      enabled: true
      runAsUser: 0
      fsGroup: 101

    ports:
    - name: application
      containerPort: 80
      protocol: TCP

    resources:
      enabled: true
      requests:
        memory: 512Mi
        cpu: 50m
      limits:
        memory: 1536Mi
        cpu: 2

    probes:
      enabled: true
      content:
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 20

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 60
          failureThreshold: 2

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 60
          failureThreshold: 2

  jobs: []